In [6]:
import pandas as pd

In [7]:
name = ['mohit', 'rahul', 'Aman']
marks = [80, 45, 60]

for i in range(len(name)):
    print('Name', name[i])
    print('Marks', marks[i])

    if marks[i] >= 50:
        print('result: pass')
    else:
        print('result: fail')

Name mohit
Marks 80
result: pass
Name rahul
Marks 45
result: fail
Name Aman
Marks 60
result: pass

In [16]:
data = pd.DataFrame({'name': ['Mohit', 'Aman', 'Rahul', 'naha'],
                    'marks': [80, 60, 45, 30],})

In [17]:
data[data['marks']>50]

    name  marks
0  Mohit     80
1   Aman     60

In [24]:
data["Result"] = ["Pass" if m >= 50 else 'Fail' for m in 
                 data['marks']]

In [25]:
data

    name  marks Result
0  Mohit     80   Pass
1   Aman     60   Pass
2  Rahul     45   Fail
3   naha     30   Fail